# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: arunim2002
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: fortune-db-server
# "service" is the name of this project. This will also be added to your AWS resource names.
service: fortune-dynamodb-server

provider:
  name: aws
  runtime: nodejs20.x

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: "*"
